[package]
name = "window"
version = "0.1.0"
authors = ["Eden Harris <aussiedwarf@gmail.com>"]
edition = "2021"

[dependencies]
rad = { path = "../../rad" }

clap = {version = "~4.3.12", features = ["derive"]}
glam = "~0.23.0"
image = "~0.24.6"
libc = "~0.2.140"

sdl2 = { version = "~0.35.2", default-features = false, features = ["static-link", "bundled", "raw-window-handle"] }
