[package]
name = "window"
version = "0.1.0"
authors = ["Eden Harris <aussiedwarf@gmail.com>"]
edition = "2024"
rust-version = "1.91"

[dependencies]
rad = { path = "../../rad" }

clap = {version = "4.5.51", features = ["derive"]}
glam = "0.30.9"
image = {version = "0.25.8", default-features = false, features = ["png", "jpeg", "bmp"]}
libc = "0.2.177"

sdl3 = { version = "0.16.1", default-features = false, features = ["ash", "static-link", "build-from-source", "raw-window-handle"] }
sdl3-sys = "0.5.10"

[target.'cfg(target_os = "emscripten")'.features]
default = ["pthread"]

