name: Rust

on:
  push:
    branches: [ "main", "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-ubuntu2204-x64:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          clean: ${{ github.event.inputs.build-clean }}
      - name: Build Debug
        uses: actions/checkout@v3
        run: cargo build --verbose
      - name: Build Release
        uses: actions/checkout@v3
        run: cargo build --verbose --release
  build-windows10-x64:
    runs-on: [self-hosted, Windows, X64]
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          clean: ${{ github.event.inputs.build-clean }}
      - name: Build Debug
        uses: actions/checkout@v3
        run: cargo build --verbose
      - name: Build Release
        uses: actions/checkout@v3
        run: cargo build --verbose --release
