name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-ubuntu2204-x64:
    runs-on: [self-hosted, Linux, X64]
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
  build-windows10-x64:
    runs-on: [self-hosted, Windows, X64]
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
